### ISSUE TITLE
Validate against WP disallowed list [FEATURE]

### ISSUE THREAD

**Issue by draney** [Highfivery/zero-spam-for-wordpress#210]
Validate a field’s value against the WordPress Comment Blacklist. This would give users an easy way to block entries containing specific words or phrases

**Comment by bmarshall511** [comment]
Update here: v5.0.7 will include functionality to auto-update this list using @splorp Comment Blacklist for WordPress (https://github.com/splorp/wordpress-comment-blacklist). 

Still have plans to use this list to validate other submissions with zero spam.
