### ISSUE TITLE
[FEATURE] Settings Page is slowly getting to big for Mobile devices.

### ISSUE THREAD

**Issue by konsti2020** [Highfivery/zero-spam-for-wordpress#294]
**Is your feature request related to a problem? Please describe.**
I manage my Homepage completely from my Smartphone. Since the complete 'blocked domain list' in the General Tab is shipped with 
the settings page it gets difficult to add new Domains, mostly the Tab just freezes.
Also the Export / Import Settings JSON feature could not be used with my Smartphone because of the needed Cache size when copying the settings.

**Describe the solution you'd like**
It would be nice if there only was a form field to add the Domains and the complete List would maybe in a different Tab. The Settings maybe could be downloaded and uploaded as a JSON file directly so it doesn't need to fit in the copy and paste Cache.

**Describe alternatives you've considered**
Another possibility would be that the settings that should be exported could be chosen - so the e-mail domain list could be avoided.

Best regards and merry Christmas

**Comment by konsti2020** [comment]
I thought of another possibility to add the Spam Domains of Spam Bots that managet it somehow to get registered to the 'blocked domain list' .
In the Users Tab you could add the option 'Mark as Spam' to the mass selection options so the mail domain of this user's will be added to the 'blocked domain list' and the users will be deleted.

**Comment by bmarshall511** [comment]
v5.4 includes major UI enhancements including a boost in the setting page load times. You can download the beta version here: https://github.com/Highfivery/zero-spam-for-wordpress/tree/5.4.0
