### ISSUE TITLE
[FEATURE] Format log date by site preference, not hard-coded to US format 

### ISSUE THREAD

**Issue by adam-marash** [Highfivery/zero-spam-for-wordpress#305]
**Is your feature request related to a problem? Please describe.**

WordPress Zero Spam displays a log at Dashboard > Zero Spam > Log. This log includes a date column. Dates in this log are presented in a fixed US format, which in the general case, will likely be inconsistent with the admin's desired preference defined under Settings > General > Date Format/Time Format. 

**Describe the solution you'd like**
The date to be presented in the format set at Settings > General > Date Format and available under `get_option( 'date_format' )` and `get_option( 'time_format' )`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bmarshall511** [comment]
@adam-marash Sorry for the delay and thanks for the catch. This will be included in the next release.
