### ISSUE TITLE
[BUG] WooCommerce registrations blocked during checkout

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [Highfivery/zero-spam-for-wordpress#313]
Hello, Ben!

Its been brought to my attention that all WooCommerce registrations made during checkout fail. And with the registration, the payment made by customers is blocked as well.
Your new way of checking WooCommerce registrations doesn't take into account that new accounts can be created during the checkout as well. Right now you are only protecting the registration form displayed under My Account.

**Plugin Configuration:**
- David Walsh Technique: Enabled
- WooCommerce Integration: Enabled

**WooCommerce Settings:**
- allow customers to create an account during checkout
- when creating an account, automatically generate an account username for the customer based on their name, surname, or email
- when creating an account, send the new user a link to set their password

**WordPress Zero Spam Log**
- Type: WooCommerce Registration
- Failed: David Walsh

PS: I don't think it really matters how WooCommerce is configured, as long as the first option (to allow customers to create an account during checkout) is enabled.

**Comment by bmarshall511** [comment]
@EusebiuOprinoiu thanks for the details, think I found an issue and pushed a fix: https://github.com/Highfivery/zero-spam-for-wordpress/pull/314

Tested on my local and looks good, can you confirm?

**Comment by EusebiuOprinoiu** [comment]
Yes. It works great!
Thanks...
