### ISSUE TITLE
Bug with last release (probably)

### ISSUE THREAD

**Issue by giuseppeyes** [Highfivery/zero-spam-for-wordpress#315]
Hello friends,

I have installed Zero Spam since 2 weeks and have accepted 7 fake address.

Today I have updated the plugin and, to improve the performance, I have set the automated configuration to check if it works not to accept other fake addresses and this happens (and then subscribe to the service as it will be a portal with thousands of Users so I need the maximum available block available).

I use my admin login on firefox and a user on chrome.

When I have tried to login on chrome it indicates to me malicious ip (i connect on mobile so I don't know the connection IPs) but at the third attempt it has crashed the website.

I have deactivated the plugin via content and the website has restarted.

I have tried to find the origin of the crash and I have deactivated the login tick in the last row and then the user on chrome (remember, same connection with the admin) connected, then I have deactivated the last tick in the last row (regarding the ip block) and the website has crashed.

Then I have deactivated the plugin and now I'm in the website again but i don't know what do to clearly. 

Do I have to leave unticked the login row? Is there something to update?

Please let me know considering that blocking the fake registration is crucial for a buddypress portal with thousand of people that register, post and comments, especially as I don't want to use Akismet or similar where any post or comment should be analyzed externally via Api.

Waiting for your kind reply,

many thanks,

Giuseppe Amodio

www.amodio.live

**Comment by giuseppeyes** [comment]
![Screenshot 2022-03-18 at 21-53-58 Zero Spam Settings ‹ Amodio live — WordPress](https://user-images.githubusercontent.com/87819525/159081871-26a6efc1-fabb-4b68-8688-6f09d28a638a.png)

With this setting does not crash. If you select "Log Blocked Login Attempts" it crashes.

Thank you,

Giuseppe

**Comment by bmarshall511** [comment]
@giuseppeyes I'm unable to replicate the issue you described. I'll need more specific details & able to replicate it to help.

Please provide the Zero Spam version you're using, an export of the Zero Spam settings, and the URL where this issue is occurring. Even better if you're able to provide a staging/testing URL where I can replicate this issue.

**Comment by giuseppeyes** [comment]
{"share_data":false,"widget_visibility":["administrator"],"block_handler":"403","block_method":"php","blocked_message":"Your IP address has been blocked due to detected spam\/malicious activity.","blocked_redirect_url":"https:\/\/wordpress.org\/plugins\/zero-spam\/","log_blocked_ips":"enabled","max_logs":"10000","ip_whitelist":false,"blocked_email_domains":false,"davidwalsh":"enabled","davidwalsh_form_selectors":false,"zerospam":"enabled","zerospam_license":false,"zerospam_timeout":"5","zerospam_cache":"14","zerospam_confidence_min":"30","stop_forum_spam":"enabled","stop_forum_spam_timeout":"5","stop_forum_spam_cache":"14","stop_forum_spam_confidence_min":"50","project_honeypot":"enabled","project_honeypot_access_key":false,"project_honeypot_cache":"14","project_honeypot_score_min":"50","ipstack_api":false,"ipstack_timeout":"5","ipstack_cache":"14","ipinfo_access_token":false,"ipinfo_cache":"14","google_api":false,"verify_comments":"enabled","comment_spam_message":"Your IP has been flagged as spam\/malicious.","log_blocked_comments":"enabled","verify_registrations":"enabled","registration_spam_message":"Your IP has been flagged as spam\/malicious.","log_blocked_registrations":"enabled","verify_login":false,"login_spam_message":"Your IP has been flagged as spam\/malicious.","log_blocked_logins":false,"debug":false,"debug_ip":false}

**Comment by giuseppeyes** [comment]
Version 5.3.2 . The difference with settings provided is that if you tick "Log Blocked Login Attempts" and you insert correct data into login website becomes unreachable. To reach the website you have to disable plugin (I do via file manager on plesk).

Amodio.live is the website.

If you want to try yourself I can give you credential as, at the worse, I have backup to recover the website. 

Please update me.

Thank you very much,

Giuseppe

**Comment by giuseppeyes** [comment]
Hi Ben,

I have not changed set but I have not received any new successfull 
attempt to registration.

Anyway I want to subscribe and I have two questions; the first is 
simple: no paypal? If not, why? Only to understand.

The second is a but more complex because I actually don't understand 
what the Zero spam upgrade does with its blacklist Api limited to 10,000 
per days. What does it mean?

Anyway please indicate me some info even if I will subscribe in any 
case.

And, finally, updating from free means I have to code something to 
connect to Api?

Apologies for this basic questions,

many thanks,

Giuseppe

On 2022-04-13 17:07, Ben Marshall wrote:

> @giuseppeyes [1] I'm still unable to reproduce this error. Do yo have a 
> staging site I could do some testing on?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>



Links:
------
[1] https://github.com/giuseppeyes
[2] 
https://github.com/Highfivery/zero-spam-for-wordpress/issues/315#issuecomment-1098167789
[3]

**Comment by bmarshall511** [comment]
@giuseppeyes Closing this, please contact info@zerospam.org regarding subscription questions.
