### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by courtchatter** [Highfivery/zero-spam-for-wordpress#316]
I use WPforms. Just looking the name entered on the form I know that it will be spam. For example RonaldArticGC RonaldArtic

Spammers seem to use a first name ending with the last 3 characters entered as lowercase uppercase uppercase or numeric uppercase uppercase.

So to stop these an additional option of a Name validation to disallow the last 3 characters of First Names ending in the character case lUU (case lowercase uppercase uppercase) or nUU (numeric uppercase uppercase) if you understand what I mean.

This feature would stop over 95% of all spam email that I receive!

**Comment by bmarshall511** [comment]
Thanks for the input! v5.4 will include enhanced security features for WPforms including the ability to use the disallowed words list to validate input against. You can download the beta version here: https://github.com/Highfivery/zero-spam-for-wordpress/tree/5.4.0

**Comment by courtchatter** [comment]
Hi Ben and thanks for the update.

However, will v5.4 specifically provide the feature that I requested in issue #316?

I see that you have closed the issue but from your reply I don’t believe that you will be providing what it is that I am requesting.

Here was my request:
I use WPforms. Just looking the name entered on the form I know that it will be spam. For example RonaldArticGC RonaldArtic
Spammers seem to use a first name ending with the last 3 characters entered as lowercase uppercase uppercase or numeric uppercase uppercase.
So to stop these an additional option of a Name validation to disallow the last 3 characters of First Names ending in the character case lUU (case lowercase uppercase uppercase) or nUU (numeric uppercase uppercase) if you understand what I mean.
This feature would stop over 95% of all spam email that I receive!

Stopping over 95% of WPforms spam is a massive gain that Zero Spam can easily achieve. Look at the picture below:


To stop these an additional option of a Name validation to disallow the last 3 characters of First Names ending in the character case lUU (case lowercase uppercase uppercase) or nUU (numeric uppercase uppercase)

If you need further explanation please let me know but the facility as I have specified is badly needed.

Regards
Colin (courtchatter)

World Justice News Administration
http://worldjusticenews.com
