### ISSUE TITLE
[FEATURE] Make it cleared how disallowed words work

### ISSUE THREAD

**Issue by courtchatter** [Highfivery/zero-spam-for-wordpress#317]
I use WPforms simple contact form and received an email that included the word porn.
To me that is a pretty basic word that I would expect to be caught by an ant-spam function. 

So I went to the Zero-Spam settings and the only option for words is "Override & Update Core Disallowed Words"
I read that as I can either Override Core Disallowed Words OR I can Update Core Disallowed Words (Add To Core Disallowed words).
So I clicked the button that says Override & Update Core Disallowed Words.

I expected to get a screen that allowed me to enter a word list that would append to the Core Disallowed Words but I didn't. What actually happened was I received a message WordPresss disallowed words list has been successfully updated to the recommended.

**So I didn't get what I expected and nor have I any idea what I have done or to reverse what I may have done.**

**Sorry if I am dumb but what have I done? The message "WordPresss disallowed words list has been successfully updated to the recommended." doesn't really explain to me something that I can understand and how can I reverse what I did by pressing that button?** 

I guess what I may be reporting is a bug or it may be a feature request to be able to add additional words to the core words list.

What it certainly identifies is that the documentation is lacking because I had to rely on guesswork to see if I could do what I wanted to do.

Additionally it identifies that an update gets applied without an Are you sure you want to do this update and also an update is applied before the Save settings is applied.  

 

**Desktop
 - Windows 10
 - Chrome
 - Version 100.0.4896.88 (Official Build) (64-bit)

**Comment by courtchatter** [comment]
So you changed the title to Make it cleared how disallowed words work (cleared is a typo request by you).

It should be clear to you then that if what I reported is not a Bug, then the Feature is what I was trying to do --- I want to add an additional word to  the disallowed words list. I don't just want you to make it clear how disallowed words work I want to be able to add an additional disallowed word.

**Comment by bmarshall511** [comment]
The next release includes significant UI enhancements and a better explanation of what does what. You can always add to the disallowed word list once populated with the recommended words from Zero Spam.
