### ISSUE TITLE
[FEATURE] Give compatibility with wpDiscuz (https://it.wordpress.org/plugins/wpdiscuz/)

### ISSUE THREAD

**Issue by PeopleInside** [Highfivery/zero-spam-for-wordpress#327]
**Is your feature request related to a problem? Please describe.**

Zero spam is not working with the plugin Comments – wpDiscuz (90.000+ installations)

**Describe the solution you'd like**

Can you fix the issue where Zero spam block the correct comments submission?
If Zero spam is active and is also active wpDiscuz (https://it.wordpress.org/plugins/wpdiscuz/) and you try to submit a comment you get:

403 Forbidden admin-ajax.php

See the following discussion:
https://wordpress.org/support/topic/comment-not-added-403-forbidden-admin-ajax-php/

**Comment by bmarshall511** [comment]
Thanks @PeopleInside for letting me know! The next version, 5.4 will have support for wpDiscuz. You can download the beta version now if you'd like: https://github.com/Highfivery/zero-spam-for-wordpress/tree/5.4.0
