### ISSUE TITLE
Question? 

### ISSUE THREAD

**Issue by courtchatter** [Highfivery/zero-spam-for-wordpress#334]
Why has issue #316 been closed? The specification for the requirement of the feature given in issue #316 was very specific.

Your reply was:
Thanks for the input! v5.4 will include enhanced security features for WPforms including the ability to use the disallowed words list to validate input against.

Issue #316 has absolutely nothing to do with words!! It is about the character string of the last 3 characters of the First Name supplied by the person sending a WPforms email.

There is nothing in v5.4 that provides this feature specified in issue #316.

Surely the specification given for the requirements of issue #316 was not hard to understand (nor that hard to provide). 

Given that the feature specified by issue #316 would stop over 95% of WPforms spam then I would think that you would be very keen to provide the feature.

Please reopen issue #316 and provide the feature as soon as possible.

**Comment by bmarshall511** [comment]
@courtchatter 

1. #316 wasn't submitted correctly, nor was this one. Please follow the instructions laid out when submitting feature/bug requests
2. As stated in #316 (https://github.com/Highfivery/zero-spam-for-wordpress/issues/316#issuecomment-1236160769) you can use the disallowed words list to accomplish this request. 
3. Adding such validation to name-specific fields is not feasible for a form plugin that doesn't require a name field (form configurations are all different from site to site, no way to automatically check a 'name' field that could be named anything)
4. If you'd like to submit a feature request for a more advanced system, by all means, do so... but please follow the instructions when doing so
