### ISSUE TITLE
[BUG] Fatal error - disable_emojis_tinymce - class-security.php (?)

### ISSUE THREAD

**Issue by yiannisc** [Highfivery/zero-spam-for-wordpress#338]
Hi,

After updating to 5.4.2 I got the following error message when I tried to add a new post:

-----------------------------------
Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "disable_emojis_tinymce" not found or invalid function name in /var/www/mjhudson.com/wp-includes/class-wp-hook.php:309 Stack trace: #0 /var/www/mjhudson.com/wp-includes/plugin.php(191): WP_Hook->apply_filters() #1 /var/www/mjhudson.com/wp-includes/script-loader.php(487): apply_filters() #2 /var/www/mjhudson.com/wp-admin/edit-form-blocks.php(252): wp_tinymce_inline_scripts() #3 /var/www/mjhudson.com/wp-admin/post-new.php(72): require('...') #4 {main} thrown in /var/www/mjhudson.com/wp-includes/class-wp-hook.php on line 309
-----------------------------------

I downgraded to 5.4.1 and it all works. Can you please resolve it?

Could it be the code on line 60 of wp-content/plugins/zero-spam/modules/security/class-security.php ?
I did a grep and this is the only instance of 'disable_emojis_tinymce' I found in my installation.
add_filter( 'tiny_mce_plugins', 'disable_emojis_tinymce' );

Many thanks,
Yiannis

**Comment by bmarshall511** [comment]
@yiannisc Thanks for notifying us. We just pushed an update that fixes this issue (https://github.com/Highfivery/zero-spam-for-wordpress/commit/7121f63489ee6d8cee1901e850b41b7a01d7a034). Let me know if the problem persists after updating to v5.4.3.

If haven't already, please submit a review for the plugin: (https://wordpress.org/support/plugin/zero-spam/reviews/?filter=5)
