### ISSUE TITLE
[BUG] PHP 8+ Compatibility with Impload parameter order

### ISSUE THREAD

**Issue by michaelbragg** [Highfivery/zero-spam-for-wordpress#341]
**Describe the bug**

As part of our upgrade to PHP8. Our scans have noticed the following incompatibility with PHP8:

> Passing the $glue and $pieces parameters in reverse order to implode has been deprecated since PHP 7.4; $glue should be the first parameter and $pieces the second
– [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility/blob/develop/PHPCompatibility/Sniffs/ParameterValues/RemovedImplodeFlexibleParamOrderSniff.php)

The offending lines of code are:
- https://github.com/Highfivery/zero-spam-for-wordpress/blob/master/core/class-utilities.php#L235
- https://github.com/Highfivery/zero-spam-for-wordpress/blob/master/core/class-utilities.php#L239

PHP depricated support for 'reverse order' in impload, eg, `impload( array $array, string $separator )`,  PHP 7.4 and remove it in PHP 8.0.

> Legacy signature (deprecated as of PHP 7.4.0, removed as of PHP 8.0.0):
[impload](https://www.php.net/manual/en/function.implode.php)

I'm unable to see where the `$denied_ips` is set within the settings area to test the code. 
Maybe this feature is no longer used?

**To Reproduce**

Simplified test case: https://3v4l.org/6AeIB

**Expected behavior**
I expect the scan not to find the error. Either by switching the parameters around or the removal of the code.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmarshall511** [comment]
@michaelbragg Thanks for bringing this up, will be fixed in the next release.
