### ISSUE TITLE
[BUG] A data query is issued instead of the blocked message 

### ISSUE THREAD

**Issue by konsti2020** [Highfivery/zero-spam-for-wordpress#342]
**Describe the bug**
From time to time I test my homepage to see if everything is working. Today Zero Spam had some unexpected behaviour. 
I tried to register myself with a blocked domain but instead of showing the Blocking page it showed what to me looks like a data request for some sort of API or PHP error message.
**The output text after clicking on register:**
Array ( [headers] => Requests_Utility_CaseInsensitiveDictionary Object ( [data:protected] => Array ( [server] => nginx [date] => Sat, 08 Oct 2022 12:55:47 GMT [content-type] => application/json; charset=UTF-8 [vary] => Accept-Encoding [x-robots-tag] => noindex [link] => ; rel="https://api.w.org/" [x-content-type-options] => nosniff [access-control-expose-headers] => X-WP-Total, X-WP-TotalPages, Link [access-control-allow-headers] => Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type [allow] => POST [x-httpd-modphp] => 1 [x-cdn-c] => static [content-encoding] => gzip [x-sg-cdn] => 1 [x-proxy-cache-info] => DT:1 [host-header] => 8441280b0c3*******98a563a7 ) ) [body] =>
Warning: json_decode() expects parameter 1 to be string, array given in /***/www/zerospam.org/public_html/wp-content/plugins/zero-spam-store/core/class-api.php on line 182
{"status":200,"response":"success","body_response":{"report_type":"email_address","report_module":"registration","report_failed":"blocked_email_domain","email_details":{"names":["inspector",""]},"report_key":"emailtothrowerror@mailcase.email","reporter_email":"****my_mail**@*****.de","app_key":"**my_page**","app_type":"wordpress","app_details":{"app_version":"6.0.2","app_type_version":"5.4.3","app_language":"de-de","app_email":"**my_mail**","app_name":"**page_title**","app_desc":"**page_subheader**"},"reporter_ip_address":"**server_ip**"}} [response] => Array ( [code] => 200 [message] => OK ) [cookies] => Array ( ) [filename] => [http_response] => WP_HTTP_Requests_Response Object ( [response:protected] => Requests_Response Object ( [body] =>
Warning: json_decode() expects parameter 1 to be string, array given in /home/customer/www/zerospam.org/public_html/wp-content/plugins/zero-spam-store/core/class-api.php on line 182
{"status":200,"response":"success","body_response":{"report_type":"email_address","report_module":"registration","report_failed":"blocked_email_domain","email_details":{"names":["inspector",""]},"report_key":"emailtothrowerror@mailcase.email","reporter_email":"**my_mail**","app_key":"**my_domain**","app_type":"wordpress","app_details":{"app_version":"6.0.2","app_type_version":"5.4.3","app_language":"de-de","app_email":"**my_mail**","app_name":"**page_title**","app_desc":"**page_subheader**"},"reporter_ip_address":"**server_ip**"}} [raw] => HTTP/1.1 200 OK Server: nginx Date: Sat, 08 Oct 2022 12:55:47 GMT Content-Type: application/json; charset=UTF-8 Transfer-Encoding: chunked Connection: close Vary: Accept-Encoding X-Robots-Tag: noindex Link: ; rel="https://api.w.org/" X-Content-Type-Options: nosniff Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages, Link Access-Control-Allow-Headers: Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type Allow: POST X-Httpd-Modphp: 1 X-CDN-C: static Content-Encoding: gzip X-SG-CDN: 1 X-Proxy-Cache-Info: DT:1 Host-Header: 8441280b0c35cbc1147f8ba998a563a7
Warning: json_decode() expects parameter 1 to be string, array given in /home/customer/www/zerospam.org/public_html/wp-content/plugins/zero-spam-store/core/class-api.php on line 182
{"status":200,"response":"success","body_response":{"report_type":"email_address","report_module":"registration","report_failed":"blocked_email_domain","email_details":{"names":["inspector",""]},"report_key":"emailtothrowerror@mailcase.email","reporter_email":"**my_mail**","app_key":"**page_domain**","app_type":"wordpress","app_details":{"app_version":"6.0.2","app_type_version":"5.4.3","app_language":"de-de","app_email":"**my_mail**","app_name":"**page_title**","app_desc":"**page_subheader**"},"reporter_ip_address":"**server_ip**"}} [headers] => Requests_Response_Headers Object ( [data:protected] => Array ( [server] => Array ( [0] => nginx ) [date] => Array ( [0] => Sat, 08 Oct 2022 12:55:47 GMT ) [content-type] => Array ( [0] => application/json; charset=UTF-8 ) [vary] => Array ( [0] => Accept-Encoding ) [x-robots-tag] => Array ( [0] => noindex ) [link] => Array ( [0] => ; rel="https://api.w.org/" ) [x-content-type-options] => Array ( [0] => nosniff ) [access-control-expose-headers] => Array ( [0] => X-WP-Total, X-WP-TotalPages, Link ) [access-control-allow-headers] => Array ( [0] => Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type ) [allow] => Array ( [0] => POST ) [x-httpd-modphp] => Array ( [0] => 1 ) [x-cdn-c] => Array ( [0] => static ) [content-encoding] => Array ( [0] => gzip ) [x-sg-cdn] => Array ( [0] => 1 ) [x-proxy-cache-info] => Array ( [0] => DT:1 ) [host-header] => Array ( [0] => 8441280b0c*****a563a7 ) ) ) [status_code] => 200 [protocol_version] => 1.1 [success] => 1 [redirects] => 0 [url] => https://www.zerospam.org/wp-json/v5.4/report/ [history] => Array ( ) [cookies] => Requests_Cookie_Jar Object ( [cookies:protected] => Array ( ) ) ) [filename:protected] => [data] => [headers] => [status] => ) )

**To Reproduce**
1. Try registration with made up or blocked E-Mail 
2. Click on 'register'
3. See error
Also happens with the WordPress comment form
but not with Contact Form 7 .

**Expected behavior**
A forwarding to the blocking Page or a given out message under the registration form as usual.

**Desktop (please complete the following information):**
Most details are up in the output message above 
 - WordPress installation
 additional plugins are 
 - Noptin Newsletter
 - Autoptimize
 - Contact Form 7 

**Smartphone (please complete the following information):**
 - OS: Android 
 - Browser Chrome 
 - Version 106

**Additional context**
As it looks so far, there is nothing dangerous to do with it except that it disturbs the frontend. The information provided could also be collected in this way via the site.

**Comment by bmarshall511** [comment]
Thanks for submitting this, it'll be fixed in the next release.
