### ISSUE TITLE
Your IP address has been blocked due to detected spam/malicious activity. [BUG]

### ISSUE THREAD

**Issue by TaTorWP** [Highfivery/zero-spam-for-wordpress#346]
Hi guys,
When I go to my website https://rbjal.com/ I am getting the following message:
**Your IP address has been blocked due to detected spam/malicious activity.**

1. Go to(https://rbjal.com/)
2. See error: Your IP address has been blocked due to detected spam/malicious activity. 
3. The error is visible on MacBook Air/ Chrome, but the website works fine on Samsung G10 phone
4. 
How to get to rid of the error?

Many thanks

**Comment by bmarshall511** [comment]
Please see https://github.com/Highfivery/zero-spam-for-wordpress/wiki/FAQ#does-wordpress-zero-spam-block-user-ips
