### ISSUE TITLE
[BUG] Valid IPs being block on comments (by David Walsh technique)

### ISSUE THREAD

**Issue by inspiredearth** [Highfivery/zero-spam-for-wordpress#349]
**Describe the bug**
I was informed by a user that they couldn't leave a comment on my site, due to "Your IP have been flagged as spam/malicious" error.

I tested posting a comment myself (from an anonymous browser session, so not logged in). I got the same error. User's IP is in the UK. Mine is in New Zealand. Neither should have been blocked.

I see in the ZeroSpam logs that it was the David Walsh method that blocked my test comment, so it's likely a Javascript problem.

**To Reproduce**
1. Enable the David Walsh method.
2. Post a comment.

**Expected behavior**
Valid IPs should not be blocked. As David Walsh method uses JS to block or allow comments, it seems to me there's an issue with that method.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Browser: Chrome
 - Version: 108.0.5359.124 (Official Build) (arm64)

**Additional context**
I am wondering is this has any relationship to the bug I reported [here (#329)](https://github.com/Highfivery/zero-spam-for-wordpress/issues/329).

**Comment by inspiredearth** [comment]
Does Zero Spam maintain it's own disallowed list, and does it enter IPs into that list?

I note that I am triggering the `disallowed_list` block **after** I was first blocked by the David Walsh method. Does Zero Spam then do something with my IP?

I ask because I see that the user I mentioned above was blocked twice. She was first blocked by David Walsh method, and then seconds later she tried to submit a second time and was then block by the `disallow_list` reason.

**Comment by leewillis77** [comment]
Most likely the same issue as #347

**Comment by bmarshall511** [comment]
@inspiredearth I've tested this with valid IPs and all seems to be working. Can you provide one of the IP addresses that's getting blocked, the URL of where the issue is & if you see any JS errors in your console?

**Comment by bmarshall511** [comment]
Haven't heard anything on this in awhile so closing.
