### ISSUE TITLE
[BUG] IP Whitelist not working

### ISSUE THREAD

**Issue by inspiredearth** [Highfivery/zero-spam-for-wordpress#350]
**Describe the bug**
After doing my test comment, as reported in issue #349, I added my IP to the "IP Whitelist".

I then tried to post a comment, with text provided by the user who was unable to post their comment due to the David Walsh method blocking them (detailed in #349).

I was again blocked. This time the reason in the log is `disallowed_list`.

**To Reproduce**
1. Add IP to `IP Whitelist`
2. Post comment with content that the disallowed_list will block (I presume this is what's required)
3. Comment is blocked due to `disallowed_list` reason.

**Expected behavior**
Once an IP is in the whitelist, that user should never be blocked, as per standard Whitelist practices.

**Additional context**
The comment that triggered this block was:
```
Hi Jonathan, thank you for posting this!

I wonder if you came across the work of Rose Rosetree before? She has a blog post where she has read the aura of some of what I would term the "maleovlent" shamans, after reading your post. https://www.rose-rosetree.com/blog/2016/07/05/ayahuasca-guillermo-arevalo-ugly-aura-2/

It is fascinating to me how similar your descriptions, and the aura readings are. She has also noted in one of her books how a lot of people have astral entities stuck to their aura.
```

I see nothing in that comment that I would expect to trigger a spam blocker.

**Comment by inspiredearth** [comment]
Does Zero Spam maintain it's own disallowed list, and does it enter IPs into that list?

I note that I am triggering the `disallowed_list` block **after** I was first blocked by the David Walsh method. Does Zero Spam then do something with my IP?

I ask because I see that the user I mentioned in issue #329 was first blocked by David Walsh method, and then she tried to submit a second time by was then block by the `disallow_list` reason.

**Comment by bmarshall511** [comment]
@inspiredearth Great catch & thanks for the detailed information. The issue was related to the debug IP filter not getting run before the comment check. This has been fixed in the next release.
