### ISSUE TITLE
your ip has been flagged as spam/malicious

### ISSUE THREAD

**Issue by JudgeCeeJay** [Highfivery/zero-spam-for-wordpress#361]
### Describe the bug

Hello, I was trying to post a comment on tenfootpole.org (hosted by WordPress) and I received a message stating that my IP has been flagged as spam/malicious.  A quick web search brought me to this forum. 

This message is happening from my home on two different laptops (personal, and work). I don't run any sort of business from my house and virus scans show all is clear.  I don't understand how I would get on such list, but in any case I'm inquiring about how I can get off of it.  

Thanks very much for your help,
    Cee-Jay
    
    PS: I apologize in advance if I'm posting this in the wrong place.  Thank you for your patience and understanding.

### Steps to Reproduce

1. Go to Tenfootpole.org
2. Post a comment from my house
3. See Error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bmarshall511** [comment]
@JudgeCeeJay 

Bummer to hear you're having issues posting a comment on tenfootpole.org. Just to clarify, Zero Spam doesn't actually block user IPs by itself. You can read more about that in our FAQ: [Zero Spam FAQ](https://wordpress.org/plugins/zero-spam/#does%20zero%20spam%20for%20wordpress%20block%20user%20ips%3F).

Your best bet is to reach out to the site owner directly. They should be able to tell you why you're getting blocked and can add you to their whitelist if needed.

Hope this clears things up and you get back to commenting soon!

Cheers,
Ben
