### ISSUE TITLE
Spam registration

### ISSUE THREAD

**Issue by lomomir** [Highfivery/zero-spam-for-wordpress#365]
### Describe your question

Thanks for your plugin. 

Please can you help me to block spam registration?

I have a Wordpress Woocommerce page with DIvi and Login and Registration plugin from Divi market. Also Google Recaptcha is activated with your plugin but i have still a spam registration from last two days. 

www.teamates.sk

Please can you help to stop that?

Thank you so much:)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bmarshall511** [comment]
@lomomir Thanks for reaching out. We've actually already had an open feature request to support Divi, you can track it here: https://github.com/Highfivery/zero-spam-for-wordpress/issues/339.
